# Generated by Django 3.2.6 on 2022-03-03 18:00

from django.db import migrations
# Generated by Django 3.2.6 on 2022-03-03 06:18

from django.db import migrations
from ..models import UserType
from datetime import datetime
from django.contrib.auth.models import AbstractUser


def populate_db(appreg, ed):
    User = appreg.get_model('OddJobs', 'User')
    Job = appreg.get_model('OddJobs', 'Job')

    # create superuser
    logan = User(first_name="Logan", last_name="Ballard", email="lo.ballard@gmail.com", username="loballard",
         is_staff=True, is_active=True, is_superuser=True, balance=150.00, type=UserType.ADMIN)
    AbstractUser.set_password(logan, "password")
    logan.save()

    # create customers
    alex = User(first_name="Alex", last_name="Hardy", email="al.hardy@gmail.com", username="alhardy",
         is_staff=False, is_active=True, is_superuser=False, balance=200.00)
    AbstractUser.set_password(alex, "password")
    alex.save()

    aaron = User(first_name="Aaron", last_name="Slade", email="ar.slade@gmail.com", username="arslade",
         is_staff=False, is_active=True, is_superuser=False, balance=0.0)
    AbstractUser.set_password(aaron, "password")
    aaron.save()

    # create workers
    matt = User(first_name="Matt", last_name="Scribner", email="ma.scribner@gmail.com", username="mascribner",
         is_staff=False, is_active=True, is_superuser=False, balance=0.0, type=UserType.WORKER)
    AbstractUser.set_password(matt, "password")
    matt.save()

    james = User(first_name="James", last_name="Squire", email="ja.squire@gmail.com", username="jasquire",
         is_staff=False, is_active=True, is_superuser=False, balance=0.0, type=UserType.WORKER)
    AbstractUser.set_password(james, "password")
    james.save()

    # create jobs
    lawn = Job(customer=alex, worker=matt, job_title="Lawn Mowing and Trimming",
               job_description="My half acre lawn needs mowing and trimming.", location="Logan, UT", price=25.00,
               start_time=datetime(2022, 2, 12), end_time=datetime(2022, 2, 19), duration=30, completed=False)
    lawn.save()

    windows = Job(customer=aaron, worker=james, job_title="Window Washing",
                  job_description="I have several large windows that need washing. A ladder is required to access them.",
                  location="West Jordan, UT", price=175.00,
                  start_time=datetime(2022, 3, 3), end_time=datetime(2022, 3, 17), duration=180, completed=False)
    windows.save()

    sheetrock = Job(customer=alex, worker=james, job_title="Basement Drywall",
                  job_description="Basement needs drywall.",
                  location="Logan, UT", price=525.00,
                  start_time=datetime(2021, 4, 20), end_time=datetime(2021, 7, 20), duration=20160, completed=True)
    sheetrock.save()

    snow_removal = Job(customer=aaron, worker=matt, job_title="Snow Removal",
                    job_description="My driveway and sidewalks need to be cleared.",
                    location="West Jordan, UT", price=35.00,
                    start_time=datetime(2021, 12, 14), end_time=datetime(2021, 12, 15), duration=60, completed=True)
    snow_removal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('OddJobs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
